language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "nightly"
before_install:
 - wget https://stockfish.s3.amazonaws.com/stockfish-6-linux.zip
 - unzip stockfish-6-linux.zip
 - mkdir -p bin
 - cp stockfish-6-linux/Linux/stockfish_6_x64 bin/stockfish
 - export PATH="`pwd`/bin:${PATH}"
 - which stockfish || (echo $PATH && false)
install:
 - pip install coveralls
 - pip install spur
script:
 - coverage run --source chess test.py --verbose
 - coverage run --source chess --append -m doctest README.rst --verbose
 - coverage run --source chess --append perft.py --verbose
after_success:
 - coveralls
